# Generated by Django 3.2.5 on 2022-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='id_cupom',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla_est',
            field=models.CharField(help_text='Unidade Federativa', max_length=2, primary_key=True, serialize=False, verbose_name='Sigla do Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='setorpro',
            name='cod_setorpro',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo sequencial do setor do produto'),
        ),
        migrations.AlterField(
            model_name='tipopro',
            name='id_tipopro',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
