# Generated by Django 3.2.5 on 2022-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220623_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condpag',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='sigla_esp',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_ven',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número sequencial da venda'),
        ),
    ]
