# Generated by Django 4.1 on 2022-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_setorpro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorpro',
            options={'ordering': ['num_setor'], 'verbose_name': 'setorpro', 'verbose_name_plural': 'setorespro'},
        ),
        #migrations.AddField(
        #    model_name='setorpro',
        #    name='id',
        #   field=models.IntegerField( default=1,null=True,serialize=False, verbose_name='ID'),
        #    preserve_default=False,
        #),
    ]
