# Generated by Django 4.1 on 2022-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_setorpro_options_setorpro_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorpro',
            options={'ordering': ['cod_pro_set'], 'verbose_name': 'setorpro', 'verbose_name_plural': 'setorespro'},
        ),
       # migrations.AddField(
       #     model_name='setorpro',
       #     name='id',
       #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
       #     preserve_default=False,
      #  ),
    ]
