# Generated by Django 4.1 on 2022-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_setorpro_options_setorpro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto1_pro',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto'),
        ),
    ]
