# Generated by Django 4.1 on 2022-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_foto1_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemven',
            name='unitario_ite',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor unitário'),
        ),
    ]
