# Generated by Django 4.1 on 2022-10-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_produto_foto1_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto1_pro',
        ),
    ]
