# Generated by Django 4.1 on 2022-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_produto_foto1_pro_setorpro_id'),
    ]

[
    ]
