# Generated by Django 4.1 on 2022-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_setorpro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='foto_cad',
            field=models.ImageField(blank=True, default='cadastros/person128.png', upload_to='cadastros/', verbose_name='Foto'),
        ),
    ]
