# Generated by Django 4.1 on 2022-11-01 13:22

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cadastro_foto_cad'),
    ]

    operations = [
            migrations.AlterField(
            model_name='itemven',
            name='quantidade_ite',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=7, verbose_name='Quantidade'),
        ),
    ]
