# Generated by Django 4.1 on 2022-11-01 13:27

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_setorpro_id_alter_itemven_quantidade_ite'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='itemven',
            name='quantidade_ite',
            field=models.IntegerField(blank=True, default=1, verbose_name='Quantidade'),
        ),
    ]
