# Generated by Django 4.1 on 2022-11-04 12:39

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_setorpro_id_alter_itemven_quantidade_ite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condpag',
            options={'ordering': ['descricao'], 'verbose_name': 'Forma de pagamento', 'verbose_name_plural': 'Formas de pagamento'},
        ),
    ]
