# Generated by Django 4.1 on 2022-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_condpag_options_setorpro_id'),
    ]

   # operations = [
    #    migrations.AddField(
    #        model_name='setorpro',
    #        name='id',
    #        field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
    #        preserve_default=False,
    #    ),
   # ]
