# Generated by Django 4.1 on 2022-12-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mov_caixa_data_emiss_mov_caixa_saldo_ant_and_more'),
    ]

    operations = [
    ]
