# Generated by Django 4.1 on 2022-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_setorpro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='teste',
            field=models.BinaryField(blank=True, null=True, verbose_name='byres de teste '),
        ),
    ]
