# Generated by Django 4.1 on 2023-01-20 16:35

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_produto_teste_setorpro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('numero_tit', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id titulos')),
                ('data_emissao_tit', models.DateTimeField(blank=True, null=True, verbose_name='data de emissao')),
                ('data_venc_tit', models.DateTimeField(blank=True, null=True, verbose_name='data de vencimento')),
                ('tipo_tit', models.CharField(blank=True, max_length=1, null=True, verbose_name='tipo de Titulos ')),
                ('conta_Ban_tit', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('caracter_tit', models.CharField(blank=True, max_length=1, null=True, verbose_name='tipo de caractere ')),
                ('tipo_mov_tit', models.CharField(blank=True, max_length=1, null=True, verbose_name='tipo de movimento ')),
                ('numero_mov_tit', models.CharField(blank=True, max_length=20, null=True, verbose_name='numero do movimento')),
                ('nf_tit', models.CharField(blank=True, max_length=30, null=True, verbose_name='nf')),
                ('cod_cad_tit', models.IntegerField(blank=True, null=True, verbose_name='codico de cadastro')),
                ('Data_baixa_tit', models.DateTimeField(blank=True, null=True, verbose_name='data da baixa ')),
                ('tipo_baixa_tit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor da baixa')),
                ('forma_baixa_tit', models.CharField(blank=True, max_length=1, null=True, verbose_name='forma da baixa')),
                ('num_doc_baixa_tit', models.CharField(blank=True, max_length=20, null=True, verbose_name='forma da baixa')),
                ('obs_tit', models.CharField(blank=True, max_length=200, null=True, verbose_name='observações ')),
            ],
        ),
    ]
