# Generated by Django 4.1 on 2023-01-23 13:51

from django.db import migrations, models
import django.db.models.deletion
import io


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_titulos_setorpro_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulos',
            options={'ordering': ['numero_tit'], 'verbose_name': 'Titulos', 'verbose_name_plural': 'titulos'},
        ),
        migrations.AddField(
            model_name='titulos',
            name='Issqn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='issqn'),
        ),
        migrations.AddField(
            model_name='titulos',
            name='cofins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='cofins '),
        ),
        migrations.AddField(
            model_name='titulos',
            name='csll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='csll '),
        ),
        migrations.AddField(
            model_name='titulos',
            name='inss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='inss '),
        ),
        migrations.AddField(
            model_name='titulos',
            name='oper_inclu',
            field=models.IntegerField(max_length=200, null=True, verbose_name='codigo de inclusao'),
        ),
        migrations.AddField(
            model_name='titulos',
            name='pis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='pis '),
        ),
        migrations.AddField(
            model_name='titulos',
            name='setor_baixa_tit',
            field=models.ForeignKey(db_column='setor_baixa_tit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_titulos', to='core.setor', verbose_name='setor_baixa_tit'),
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id_saldos', models.AutoField(primary_key=True, serialize=False, verbose_name='id do saldo ')),
                ('data_sal', models.DateTimeField(blank=True, null=True, verbose_name='data do saldo ')),
                ('caracter_salvar', models.CharField(blank=True, max_length=1, null=True, verbose_name='caracter para salvar')),
                ('Banco_sal', models.IntegerField(blank=True, null=True, verbose_name='id do banco')),
                ('saldo_sal', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='valor do saldo ')),
                ('num_folha_sal', models.IntegerField(blank=True, null=True, verbose_name='numero da folha de OS ')),
                ('Troco_sal', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='valor do troco inicial ')),
                ('Supri_cheque_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor de cheque ')),
                ('Supri_din_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor em dinheiro ')),
                ('Sangria_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sangria')),
                ('transf_ent_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Transferencia entrada ')),
                ('Transf_Said_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='transferencia saida ')),
                ('Setor_sal', models.ForeignKey(db_column='Setor_sal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_saldos', to='core.setor', verbose_name='Setor_sal')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
                'ordering': ['data_sal'],
            },
        ),
    ]
