# Generated by Django 4.1 on 2023-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_setorpro_id_alter_titulos_data_emissao_tit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulos',
            name='tipo_mov_tit',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='tipo de movimento '),
        ),
    ]
