# Generated by Django 4.1 on 2023-02-17 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_setorpro_id_alter_titulos_tipo_mov_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_caixa',
            name='data_emiss',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='data de emissao'),
        ),
    ]
