# Generated by Django 4.1 on 2023-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_setorpro_id_alter_mov_caixa_data_emiss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulos',
            name='Data_baixa_tit',
            field=models.DateField(blank=True, null=True, verbose_name='data da baixa '),
        ),
    ]
