# Generated by Django 4.1 on 2023-02-17 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_titulos_data_baixa_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_caixa',
            name='data_emiss',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='data de emissao'),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='Data_baixa_tit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data da baixa '),
        ),
    ]
