# Generated by Django 4.1 on 2023-03-07 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_setorpro_id_alter_mov_caixa_data_emiss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mov_caixa',
            name='usu_alt',
            field=models.ForeignKey(db_column='cod_usu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_USU_mov', to=settings.AUTH_USER_MODEL, verbose_name='usuario do movimento'),
        ),
        migrations.AlterField(
            model_name='mov_caixa',
            name='data_mov',
            field=models.DateTimeField(verbose_name='data do movimento do caixa'),
        ),
        migrations.AlterField(
            model_name='mov_caixa',
            name='mov',
            field=models.IntegerField(blank=True, null=True, verbose_name='movimento do caixa '),
        ),
    ]
