# Generated by Django 4.1 on 2022-08-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setor_usu',
            field=models.ForeignKey(db_column='setor_usu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_user', to='core.setor', verbose_name='setor_user'),
        ),
    ]
