# Generated by Django 4.1 on 2022-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_setor_usu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_usu',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/int:pk', verbose_name='Foto'),
        ),
    ]
