# Generated by Django 4.1 on 2022-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_foto_usu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_usu',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/{self}', verbose_name='Foto'),
        ),
    ]
