# Generated by Django 4.1 on 2022-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_foto_usu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_usu',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_usu',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/<django.db.models.fields.CharField>', verbose_name='Foto'),
        ),
    ]
