# Generated by Django 4.1 on 2022-11-25 12:32

from django.db import migrations, models
import vendas.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_nome_usu_alter_user_foto_usu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_emp',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.users.models.upload_image_bock, verbose_name='Foto da empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_usu',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.users.models.upload_image_bock, verbose_name='Foto'),
        ),
    ]
