# Generated by Django 4.1 on 2022-11-25 13:47

from django.db import migrations, models
import vendas.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_foto_emp_alter_user_foto_usu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reconhece_1',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.users.models.upload_image_bock, verbose_name='reconhecimento 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='reconhece_2',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.users.models.upload_image_bock, verbose_name='reconhecimento 2'),
        ),
    ]
