# Generated by Django 4.1 on 2022-11-25 13:48

from django.db import migrations, models
import vendas.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_reconhece_1_user_reconhece_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reconhece_1',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.users.models.upload_image_reconhece, verbose_name='reconhecimento 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reconhece_2',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.users.models.upload_image_reconhece, verbose_name='reconhecimento 2'),
        ),
    ]
