# Generated by Django 4.1 on 2022-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_reconhece_1_alter_user_reconhece_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_teste',
            field=models.FileField(null=True, upload_to='', verbose_name='arquivo de testes'),
        ),
    ]
