# Generated by Django 3.2.5 on 2022-08-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Cadastros',
        ),
        migrations.AlterModelOptions(
            name='cadastros',
            options={'verbose_name': 'cadastro', 'verbose_name_plural': 'cadastros'},
        ),
    ]
